"""add refresh lock and rate limit fields to user integrations

Revision ID: dfdbced2fa83
Revises: 6dba80a8a984
Create Date: 2026-02-05 23:40:29.849612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dfdbced2fa83'
down_revision = '6dba80a8a984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_integrations', sa.Column('refresh_locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_integrations', sa.Column('last_refresh_attempt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_integrations', 'last_refresh_attempt')
    op.drop_column('user_integrations', 'refresh_locked_at')
    # ### end Alembic commands ###
